"""
Utility modules for Beauty Salon Expense Manager.
"""

from .formatters import (
    format_currency,
    format_date,
    format_datetime,
    format_date_iso,
    parse_date,
    parse_date_iso,
    parse_date_flexible,
    truncate_text,
    format_percentage,
    format_number,
    format_integer,
    format_period,
    format_period_short,
    format_tags,
    parse_tags,
    format_file_size,
    format_duration,
    format_day_of_week,
    format_change,
    sanitize_filename
)

from .exceptions import (
    ExpenseError,
    ValidationError,
    MultipleValidationError,
    FileError,
    DataFileNotFoundError,
    DataFilePermissionError,
    DataFileCorruptedError,
    DataIntegrityError,
    DuplicateRecordError,
    BudgetError,
    BudgetExceededError,
    BudgetWarningError,
    BudgetNotFoundError,
    ExportError,
    DataImportError,
    BackupError,
    RestoreError,
    ConfigurationError,
    RecurringExpenseError,
    TemplateError,
    TemplateNotFoundError,
    DiskSpaceError,
    OperationCancelledError
)

from .validators import (
    validate_amount,
    validate_date,
    validate_category,
    validate_subcategory,
    validate_payment_method,
    validate_vendor,
    validate_description,
    validate_tags,
    validate_recurring_type,
    validate_recurring_action,
    validate_expense,
    validate_budget_amount,
    validate_threshold,
    validate_budget,
    validate_template,
    sanitize_string
)

from .error_handler import (
    ErrorHandler,
    get_error_handler,
    handle_error,
    log_error,
    log_warning,
    log_info,
    log_debug
)

from .data_correction import (
    DataCorrection,
    DataCorrectionService,
    validate_and_correct_expenses,
    validate_and_correct_budgets
)

__all__ = [
    # Formatters
    'format_currency',
    'format_date',
    'format_datetime',
    'format_date_iso',
    'parse_date',
    'parse_date_iso',
    'parse_date_flexible',
    'truncate_text',
    'format_percentage',
    'format_number',
    'format_integer',
    'format_period',
    'format_period_short',
    'format_tags',
    'parse_tags',
    'format_file_size',
    'format_duration',
    'format_day_of_week',
    'format_change',
    'sanitize_filename',
    # Exceptions
    'ExpenseError',
    'ValidationError',
    'MultipleValidationError',
    'FileError',
    'DataFileNotFoundError',
    'DataFilePermissionError',
    'DataFileCorruptedError',
    'DataIntegrityError',
    'DuplicateRecordError',
    'BudgetError',
    'BudgetExceededError',
    'BudgetWarningError',
    'BudgetNotFoundError',
    'ExportError',
    'DataImportError',
    'BackupError',
    'RestoreError',
    'ConfigurationError',
    'RecurringExpenseError',
    'TemplateError',
    'TemplateNotFoundError',
    'DiskSpaceError',
    'OperationCancelledError',
    # Validators
    'validate_amount',
    'validate_date',
    'validate_category',
    'validate_subcategory',
    'validate_payment_method',
    'validate_vendor',
    'validate_description',
    'validate_tags',
    'validate_recurring_type',
    'validate_recurring_action',
    'validate_expense',
    'validate_budget_amount',
    'validate_threshold',
    'validate_budget',
    'validate_template',
    'sanitize_string',
    # Error Handler
    'ErrorHandler',
    'get_error_handler',
    'handle_error',
    'log_error',
    'log_warning',
    'log_info',
    'log_debug',
    # Data Correction
    'DataCorrection',
    'DataCorrectionService',
    'validate_and_correct_expenses',
    'validate_and_correct_budgets'
]
